export const movies = [
    {
        id: 1,
        title: "Inception",
        director: "Christopher Nolan",
        genre: "Science Fiction",
        release_year: 2010,
        abstract: "A skilled thief is offered a chance to have his criminal history erased if he can successfully perform an almost impossible task: inception.",
        image: "",
        created_at: "2023-12-10T12:00:00Z",
        updated_at: "2023-12-10T12:00:00Z",
    },
    {
        id: 2,
        title: "The Shawshank Redemption",
        director: "Frank Darabont",
        genre: "Drama",
        release_year: 1994,
        abstract: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
        image: "",
        created_at: "2023-12-10T12:00:00Z",
        updated_at: "2023-12-10T12:00:00Z",
    },
    {
        id: 3,
        title: "The Godfather",
        director: "Francis Ford Coppola",
        genre: "Crime",
        release_year: 1972,
        abstract: "The aging patriarch of an organized crime dynasty transfers control of his empire to his reluctant son.",
        image: "",
        created_at: "2023-12-10T12:00:00Z",
        updated_at: "2023-12-10T12:00:00Z",
    },
    {
        id: 4,
        title: "The Dark Knight",
        director: "Christopher Nolan",
        genre: "Action",
        release_year: 2008,
        abstract: "When the menace known as the Joker emerges, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
        image: "",
        created_at: "2023-12-10T12:00:00Z",
        updated_at: "2023-12-10T12:00:00Z",
    },
    {
        id: 5,
        title: "Pulp Fiction",
        director: "Quentin Tarantino",
        genre: "Crime",
        release_year: 1994,
        abstract: "The lives of two mob hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in tales of violence and redemption.",
        image: "",
        created_at: "2023-12-10T12:00:00Z",
        updated_at: "2023-12-10T12:00:00Z",
    },

];